### ISSUE TITLE
Theme picker UI refactor

### ISSUE THREAD

**Issue by FrontEndCoffee** [paracycle/slackthemes#217]
The application is basically a UI clone of slack, except for the theme picker.

I think a UI refactor of the theme picker can give the site a fresh updated look! With some small changes you might get:

![screen shot 2018-11-05 at 21 46 42](https://user-images.githubusercontent.com/16303480/48025732-84646d80-e144-11e8-884d-3a723f1d201a.png)

**Comment by paracycle** [comment]
I've been thinking along these lines, but I would like to port the recent changes from the Slack UI before we even think about doing that. The Slack UI has a slicker interface for theme selection that is also responsive now, but I can't find the time to extract the HTML/CSS necessary to port it to Slackthemes. Such a port would also include the team switcher sidebar as well.

Once that is done, we can think about how we can add extra UI elements like Search, Copy, etc.

Do you think you have the time and the motivation to do that port? 😉

**Comment by FrontEndCoffee** [comment]
Sure thing! The upcoming week will be very busy for me, but next week I'll take a look at it

**Comment by Hipska** [comment]
As the Slack UI has changed a bit, you can have a second look on this and implement it?

**Comment by paracycle** [comment]
After more than 2 years, I have finally updated the Slack UI on the site. I've already added a `Copy` button that copies the hex codes, but haven't changed the UI much more beyond that.

So I will close this issue, since I feel we have gotten adequately close to the original request. If you feel otherwise, feel free to comment and reopen.

Thanks for your contributions.
